require('dotenv').config();

const {
    PORT,
    DB_HOST,
    DB_USER,
    DB_DATABASE,
    DB_PASSWORD,
    DB_PORT, 
    DB_DIALECT, 
    HEROKU_POSTGRESQL_BRONZE_URL 
} = process.env;
const INTERNEL_SERVER_ERROR = 500;
const OK = 200;
const CREATED = 201;
const NOT_CONTENT = 204;
const NOT_FOUND = 404;
const FORBIDDEN = 403;
const UNPROCESSABLE_ENTITY = 422;

exports.PORT = PORT || 8080;
exports.DB_HOST = DB_HOST;
exports.DB_USER = DB_USER;
exports.DB_DATABASE = DB_DATABASE;
exports.DB_PASSWORD = DB_PASSWORD;
exports.DB_PORT = DB_PORT;
exports.DB_DIALECT = DB_DIALECT;
exports.INTERNEL_SERVER_ERROR = INTERNEL_SERVER_ERROR;
exports.OK = OK;
exports.CREATED = CREATED;
exports.NOT_CONTENT = NOT_CONTENT;
exports.NOT_FOUND = NOT_FOUND;
exports.FORBIDDEN = FORBIDDEN;
exports.UNPROCESSABLE_ENTITY = UNPROCESSABLE_ENTITY;
exports.HEROKU_POSTGRESQL_BRONZE_URL = HEROKU_POSTGRESQL_BRONZE_URL;